---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - pvc.yaml
  - cron-job.yaml
  # - job.yaml # Argo App → Actions → Create Resource → paste the Job and set BACKUP_FILE.
